---
- name: Install dependencies for Vagrant virtualization
  dnf:
    name: "{{ vagrant_dependencies }}"
    state: present

- name: Enable + start libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Download Miniconda installation script
  get_url:
    url: "{{ miniconda_url }}"
    dest: ~/dl