- name: ensure that user is present and has right groups
  user:
    state: present
    name: {{ username }}
    comment: {{ gecos }}
    groups: {{ groups }}
    shell: {{ shell }}
    append: yes

- name: remove default home directories
  file:
    path: "{{ home_prefix }}/{{ username }}/{{ item }}"
    state: absent
  loop:
    - {{ home_absent }}

- name: create new home directories
  file:
    path: "{{ home_prefix }}/{{ username }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group:  {{ username }}
    mode: "0755"
  loop:
    - {{ home_present }}
  notify: run xdg-user-dirs-update

- name: create .ssh directory
  file:
    path: "{{ home_prefix }}/{{ username }}/.ssh"
    state: directory
    owner: {{ username }}
    group: {{ username }}
    mode: "0700"

- name: create id_rsa
  file:
    path: "{{ home_prefix }}/{{ username }}/.ssh/id_rsa"
    state: file
    owner: {{ username }}
    group: {{ username }}
    mode: "0600"

- name: create id_rsa.pub
  file:
    path: "{{ home_prefix }}/{{ username }}/.ssh/id_rsa.pub"
    state: file
    owner: {{ username }}
    group: {{ username }}
    mode: "0700"

- name: move config files