- name: ensure that wheel group exists
  group:
    name: wheel
    state: present
  become: true

- name: ensure nopasswd for wheel
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: disable sshd

- name: configure firewall
