- name: set hostname
  hostname:
    name: "{{ hostname }}"
    use: systemd  

- name: ensure that wheel group exists
  group:
    name: wheel
    state: present
  become: true

- name: ensure nopasswd for wheel
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: disable sshd
  systemd:
    name: sshd
    state: stopped
    enabled: no
  become: true

- name: enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  become: true

- name: disable firewalld services
  # TODO: use ansible.posix.firewalld
  # bindings are there on silverblue 34
  shell: "firewall-cmd  --permanent --remove-service={{ firewalld_services_disable }}"
  become: true

- name: enable firewalld services
  shell: "firewall-cmd  --permanent --add-service={{ firewalld_services_enable }}"
  become: true

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
  become: true
